version: "3"

volumes:
  postgres_database :
     external: false
  mysql_data : {}
  schemas:
    external: false
services:
  web:
    image: nginx:latest
    container_name: "pv_nginx"
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links: ['php']
  php:
    container_name: "pv_php"
    build:
      context : ./
      dockerfile : Dockerfile
    volumes:
      - ./:/code
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: [ "postgres"]
  postgres:
    container_name: "pv_postgres"
    image: ntboes/postgres-uuid
    ports:
      - "5433:5432"
    volumes:
      - postgres_database:/var/postgres_database
    environment:
      - PGDATA=/var/postgres_database
      - POSTGRES_PASSWORD=prodigyview
      - POSTGRES_USER=prodigyview
      - POSTGRES_DB=prodigyview
    restart: always
  adminer:
    container_name: "pv_adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    container_name: "pv_redis"
    image: redis:latest
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: "pv_mongodb"
    environment:
        - AUTH=yes
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_ADMIN_USER=prodigyview
        - MONGODB_ADMIN_PASS=prodigyview
        - MONGODB_APPLICATION_DATABASE=prodigyview
        - MONGODB_APPLICATION_USER=prodigyview
        - MONGODB_APPLICATION_PASSWORD=prodigyview
        - MONGODB_USER=prodigyview
        - MONGODB_PASS=prodigyview
        - MONGO_INITDB_ROOT_USERNAME=prodigyview
        - MONGO_INITDB_ROOT_PASSWORD=prodigyview
        - MONGO_INITDB_DATABASE=prodigyview
    volumes:
        - ./data/db:/data/db
    ports:
          - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  mysql:
    container_name: "pv_mysql"
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prodigyview
      MYSQL_DATABASE: prodigyview
      MYSQL_USER: prodigyview
      MYSQL_PASSWORD: prodigyview
    ports:
      - "3307:3306"